import { db } from '@/db';
import { sweets } from '@/db/schema';

async function main() {
    const indianSweets = [
        {
            name: 'Gulab Jamun',
            category: 'Indian Sweet',
            price: 250,
            quantity: 120,
            description: 'Soft, spongy milk-solid balls deep-fried and soaked in fragrant rose-cardamom sugar syrup. A beloved dessert served at weddings, festivals, and celebrations across India.',
            imageUrl: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Rasgulla',
            category: 'Indian Sweet',
            price: 180,
            quantity: 95,
            description: 'Light and spongy cottage cheese balls cooked in sugar syrup, originating from Bengal. These white, juicy spheres melt in your mouth with their delicate sweetness.',
            imageUrl: null,
            createdAt: new Date('2024-01-06').toISOString(),
            updatedAt: new Date('2024-01-06').toISOString(),
        },
        {
            name: 'Jalebi',
            category: 'Indian Sweet',
            price: 200,
            quantity: 75,
            description: 'Crispy, bright orange spirals made from fermented batter, deep-fried and soaked in saffron-infused sugar syrup. Best enjoyed warm, especially during festive seasons.',
            imageUrl: null,
            createdAt: new Date('2024-01-07').toISOString(),
            updatedAt: new Date('2024-01-07').toISOString(),
        },
        {
            name: 'Kaju Katli',
            category: 'Indian Sweet',
            price: 800,
            quantity: 45,
            description: 'Diamond-shaped premium sweet made from finely ground cashew nuts, sugar, and ghee. Often adorned with edible silver leaf, this rich delicacy is a favorite Diwali gift.',
            imageUrl: null,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            name: 'Besan Ladoo',
            category: 'Indian Sweet',
            price: 300,
            quantity: 110,
            description: 'Golden spherical sweets made from roasted chickpea flour, ghee, sugar, and cardamom. A traditional treat prepared during festivals and offered to deities.',
            imageUrl: null,
            createdAt: new Date('2024-01-09').toISOString(),
            updatedAt: new Date('2024-01-09').toISOString(),
        },
        {
            name: 'Motichoor Ladoo',
            category: 'Indian Sweet',
            price: 280,
            quantity: 88,
            description: 'Vibrant orange spherical sweets made from tiny gram flour pearls (boondi), drenched in sugar syrup with cardamom and saffron. Popular at weddings and religious ceremonies.',
            imageUrl: null,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Coconut Ladoo',
            category: 'Indian Sweet',
            price: 220,
            quantity: 65,
            description: 'Sweet balls made from fresh coconut, condensed milk, and cardamom. Simple yet delicious, these are often prepared for Lord Ganesha during festivals.',
            imageUrl: null,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            name: 'Sandesh',
            category: 'Indian Sweet',
            price: 320,
            quantity: 42,
            description: 'Delicate Bengali sweet made from fresh chhena (cottage cheese) and sugar, flavored with saffron or fruit essences. Soft texture with subtle sweetness, perfect for afternoon tea.',
            imageUrl: null,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Peda',
            category: 'Indian Sweet',
            price: 350,
            quantity: 70,
            description: 'Rich, semi-soft rounds made from khoya (reduced milk), sugar, and cardamom. Mathura Peda is especially famous, often offered at temples and given as prasad.',
            imageUrl: null,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            name: 'Mysore Pak',
            category: 'Indian Sweet',
            price: 450,
            quantity: 38,
            description: 'A melt-in-mouth South Indian delicacy made from generous amounts of ghee, gram flour, and sugar. Originated in the Mysore Palace kitchens, known for its porous, fudge-like texture.',
            imageUrl: null,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            name: 'Soan Papdi',
            category: 'Indian Sweet',
            price: 240,
            quantity: 55,
            description: 'Flaky, crisp layers of sweet confection made from gram flour, sugar, ghee, and cardamom. This delicate treat crumbles at the slightest touch and dissolves sweetly on the tongue.',
            imageUrl: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Kalakand',
            category: 'Indian Sweet',
            price: 380,
            quantity: 50,
            description: 'Soft, grainy milk cake made by reducing milk with paneer and sugar. Originating from Alwar, Rajasthan, this white sweet has a unique granular texture and mild sweetness.',
            imageUrl: null,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Gajar Halwa',
            category: 'Indian Sweet',
            price: 420,
            quantity: 30,
            description: 'Luxurious carrot pudding slow-cooked with milk, ghee, sugar, and garnished with nuts. A winter specialty, especially popular during celebrations, served warm with rabri or ice cream.',
            imageUrl: null,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Rasmalai',
            category: 'Indian Sweet',
            price: 400,
            quantity: 28,
            description: 'Soft paneer patties soaked in creamy, saffron-flavored sweetened milk (rabri), garnished with pistachios and almonds. A Bengali specialty perfect for special occasions.',
            imageUrl: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Kheer',
            category: 'Indian Sweet',
            price: 180,
            quantity: 60,
            description: 'Creamy rice pudding made by simmering rice in milk with sugar, cardamom, and saffron, garnished with nuts and raisins. A traditional dessert served at festivals and family gatherings.',
            imageUrl: null,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Petha',
            category: 'Indian Sweet',
            price: 260,
            quantity: 48,
            description: 'Translucent, soft candy made from ash gourd, originating from Agra. Available in various flavors like saffron, rose, and coconut, this unique sweet has a chewy, succulent texture.',
            imageUrl: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Coconut Barfi',
            category: 'Indian Sweet',
            price: 290,
            quantity: 12,
            description: 'Colorful, diamond-shaped fudge made from desiccated coconut, condensed milk, and ghee. Often layered in pink and white, this sweet is a festive favorite.',
            imageUrl: null,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            name: 'Milk Barfi',
            category: 'Indian Sweet',
            price: 340,
            quantity: 8,
            description: 'Dense, fudge-like squares made from khoya (milk solids), sugar, and ghee, flavored with cardamom. Rich and creamy, often decorated with pistachios and almonds.',
            imageUrl: null,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Gulab Pak',
            category: 'Indian Sweet',
            price: 500,
            quantity: 5,
            description: 'Rare and luxurious sweet made from rose petals, khoya, sugar, and dry fruits. A specialty from Rajasthan, traditionally prepared during winter months with medicinal properties.',
            imageUrl: null,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            name: 'Rava Ladoo',
            category: 'Indian Sweet',
            price: 220,
            quantity: 0,
            description: 'Spherical sweets made from roasted semolina, ghee, sugar, and cardamom, studded with cashews and raisins. Quick to prepare and popular during festivals. Currently out of stock.',
            imageUrl: null,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        }
    ];

    await db.insert(sweets).values(indianSweets);
    
    console.log('✅ Indian sweets seeder completed successfully - 20 new sweets added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});